In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving IBM HR.csv to IBM HR (1).csv

In [ ]:
uploaded.keys()

dict_keys(['IBM HR (1).csv'])

In [ ]:
df = pd.read_csv('IBM HR (1).csv')

In [ ]:
df

,Unnamed: 0,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,YearsSinceLastPromotion,YearsWithCurrManager,DailyRateGroups,HourlyRateGroups,MonthlyIncomeGroups,MonthlyRateGroups,TotalWorkingYearsGroups,YearsAtCompanyGroups,AgeGroups,YearsBeforeCompanyGroups
0,0,41,Yes,Travel_Rarely,1102,Sales,1,College,Life Sciences,1,...,0,5,K - 1100 => 1200,I - 90 => 100,E - 5000 => 6000,S - 19000 => 20000,D - 6 => 10 Years,D - 6 => 10 Years,E - 41 => 50 Years,B - 2 => 3 Years
1,1,49,No,Travel_Frequently,279,Research & Development,8,Below College,Life Sciences,1,...,1,7,B - 200 => 300,F - 60 => 70,E - 5000 => 6000,X - 24000 => 25000,D - 6 => 10 Years,D - 6 => 10 Years,E - 41 => 50 Years,B - 2 => 3 Years
2,2,37,Yes,Travel_Rarely,1373,Research & Development,2,College,Other,1,...,0,0,M - 1300 => 1400,I - 90 => 100,B - 2000 => 3000,B - 2000 => 3000,D - 6 => 10 Years,A - 0 => 1 Year,D - 31 => 40 Years,B - 2 => 3 Years
3,3,33,No,Travel_Frequently,1392,Research & Development,3,Master,Life Sciences,1,...,3,0,M - 1300 => 1400,E - 50 => 60,B - 2000 => 3000,W - 23000 => 24000,D - 6 => 10 Years,D - 6 => 10 Years,D - 31 => 40 Years,B - 2 => 3 Years
4,4,27,No,Travel_Rarely,591,Research & Development,2,Below College,Medical,1,...,2,2,E - 500 => 600,C - 30 => 40,C - 3000 => 4000,P - 16000 => 17000,D - 6 => 10 Years,B - 2 => 3 Years,C - 26 => 30 Years,B - 2 => 3 Years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1465,36,No,Travel_Frequently,884,Research & Development,23,College,Medical,1,...,0,3,H - 800 => 900,D - 40 => 50,B - 2000 => 3000,L - 12000 => 13000,F - 16 => 20 Years,C - 4 => 5 Years,D - 31 => 40 Years,B - 2 => 3 Years
1466,1466,39,No,Travel_Rarely,613,Research & Development,6,Below College,Medical,1,...,1,7,F - 600 => 700,D - 40 => 50,I - 9000 => 10000,U - 21000 => 22000,D - 6 => 10 Years,D - 6 => 10 Years,D - 31 => 40 Years,B - 2 => 3 Years
1467,1467,27,No,Travel_Rarely,155,Research & Development,4,Bachelor,Life Sciences,1,...,0,3,A - 100 => 200,H - 80 => 90,F - 6000 => 7000,E - 5000 => 6000,D - 6 => 10 Years,D - 6 => 10 Years,C - 26 => 30 Years,B - 2 => 3 Years
1468,1468,49,No,Travel_Frequently,1023,Sales,2,Bachelor,Medical,1,...,0,8,J - 1000 => 1100,F - 60 => 70,E - 5000 => 6000,M - 13000 => 14000,F - 16 => 20 Years,D - 6 => 10 Years,E - 41 => 50 Years,B - 2 => 3 Years
1469,1469,34,No,Travel_Rarely,628,Research & Development,8,Bachelor,Medical,1,...,1,2,F - 600 => 700,H - 80 => 90,D - 4000 => 5000,J - 10000 => 11000,D - 6 => 10 Years,C - 4 => 5 Years,D - 31 => 40 Years,B - 2 => 3 Years

In [ ]:
df.dtypes

Unnamed: 0                   int64
Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                   object
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                    object
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsBeforeCompany           int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
DailyRateGroups             object
HourlyRateGroups            object
MonthlyIncomeGroups         object
MonthlyRateGroups           object
TotalWorkingYearsGroups     object
YearsAtCompanyGroups        object
AgeGroups                   object
YearsBeforeCompanyGroups    object
dtype: object

In [ ]:
df.ndim

2

In [ ]:
df.isnull().sum()

Unnamed: 0                  0
Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsBeforeCompany          0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
DailyRateGroups             0
HourlyRateGroups            0
MonthlyIncomeGroups         0
MonthlyRateGroups           0
TotalWorkingYearsGroups     0
YearsAtCompanyGroups        0
AgeGroups                   0
YearsBeforeCompanyGroups    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [ ]:
x=df.drop('Attrition',axis=1)
y=df['Attrition']

In [ ]:
x

,Unnamed: 0,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,YearsSinceLastPromotion,YearsWithCurrManager,DailyRateGroups,HourlyRateGroups,MonthlyIncomeGroups,MonthlyRateGroups,TotalWorkingYearsGroups,YearsAtCompanyGroups,AgeGroups,YearsBeforeCompanyGroups
0,0,41,2,1102,2,1,2,1,1,1,...,0,5,10,7,4,17,3,3,4,0
1,1,49,1,279,1,8,1,1,1,2,...,1,7,1,4,4,22,3,3,4,0
2,2,37,2,1373,1,2,2,4,1,4,...,0,0,12,7,1,0,3,0,3,0
3,3,33,1,1392,1,3,3,1,1,5,...,3,0,12,3,1,21,3,3,3,0
4,4,27,2,591,1,2,1,3,1,7,...,2,2,4,1,2,14,3,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1465,36,1,884,1,23,2,3,1,2061,...,0,3,7,2,1,10,5,2,3,0
1466,1466,39,2,613,1,6,1,3,1,2062,...,1,7,5,2,8,19,3,3,3,0
1467,1467,27,2,155,1,4,0,1,1,2064,...,0,3,0,6,5,3,3,3,2,0
1468,1468,49,1,1023,2,2,0,3,1,2065,...,0,8,9,4,4,11,5,3,4,0
1469,1469,34,2,628,1,8,0,3,1,2068,...,1,2,5,6,3,8,3,2,3,0

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['Accuracy']
)

In [ ]:
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - Accuracy: 0.8922 - loss: 0.2831 - val_Accuracy: 0.9068 - val_loss: 0.3016
Epoch 2/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9208 - loss: 0.2179 - val_Accuracy: 0.8898 - val_loss: 0.3072
Epoch 3/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9138 - loss: 0.2304 - val_Accuracy: 0.8771 - val_loss: 0.3127
Epoch 4/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9254 - loss: 0.2100 - val_Accuracy: 0.8729 - val_loss: 0.3164
Epoch 5/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9140 - loss: 0.2145 - val_Accuracy: 0.8602 - val_loss: 0.3213
Epoch 6/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9165 - loss: 0.2284 - val_Accuracy: 0.8602 - val_loss: 0.3262
Epoch 7/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9279 - loss: 0.2018 - val_Accuracy: 0.8602 - val_loss: 0.3313
Epoch 8/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9238 - loss: 0.2060 - val_Accuracy: 0.8559 - val_loss: 0.3371
Epoch 9/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9383 - loss: 0.1967 - val_Accuracy: 0.8559 - val_loss: 0.3373
Epoch 10/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9348 - loss: 0.1877 - val_Accuracy: 0.8559 - val_loss: 0.3477
Epoch 11/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9509 - loss: 0.1496 - val_Accuracy: 0.8390 - val_loss: 0.3453
Epoch 12/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9508 - loss: 0.1625 - val_Accuracy: 0.8559 - val_loss: 0.3537
Epoch 13/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9412 - loss: 0.1685 - val_Accuracy: 0.8475 - val_loss: 0.3529
Epoch 14/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9541 - loss: 0.1509 - val_Accuracy: 0.8390 - val_loss: 0.3576
Epoch 15/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9467 - loss: 0.1663 - val_Accuracy: 0.8517 - val_loss: 0.3689
Epoch 16/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9497 - loss: 0.1501 - val_Accuracy: 0.8305 - val_loss: 0.3681
Epoch 17/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9618 - loss: 0.1498 - val_Accuracy: 0.8475 - val_loss: 0.3746
Epoch 18/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9533 - loss: 0.1577 - val_Accuracy: 0.8475 - val_loss: 0.3849
Epoch 19/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9650 - loss: 0.1313 - val_Accuracy: 0.8432 - val_loss: 0.3894
Epoch 20/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9636 - loss: 0.1235 - val_Accuracy: 0.8475 - val_loss: 0.3979

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.8807 - loss: 0.3295
Test Accuracy: 0.884353756904602

In [ ]:
y_pred = (model.predict(x_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Accuracy: 0.8843537414965986

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.96      0.93       244
           1       0.74      0.50      0.60        50

    accuracy                           0.88       294
   macro avg       0.82      0.73      0.76       294
weighted avg       0.88      0.88      0.88       294


Confusion Matrix:
 [[235   9]
 [ 25  25]]

In [ ]:
model2 = Sequential([
    Dense(128, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['Accuracy']
)

In [ ]:
history2 = model2.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - Accuracy: 0.7238 - loss: 0.5490 - val_Accuracy: 0.8008 - val_loss: 0.5011
Epoch 2/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.8527 - loss: 0.3751 - val_Accuracy: 0.8008 - val_loss: 0.4467
Epoch 3/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.8538 - loss: 0.3402 - val_Accuracy: 0.8178 - val_loss: 0.4241
Epoch 4/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.8887 - loss: 0.2916 - val_Accuracy: 0.8390 - val_loss: 0.4164
Epoch 5/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9043 - loss: 0.2687 - val_Accuracy: 0.8178 - val_loss: 0.4000
Epoch 6/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.9137 - loss: 0.2208 - val_Accuracy: 0.8263 - val_loss: 0.4122
Epoch 7/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9227 - loss: 0.2185 - val_Accuracy: 0.8305 - val_loss: 0.4232
Epoch 8/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9289 - loss: 0.1895 - val_Accuracy: 0.8263 - val_loss: 0.4130
Epoch 9/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9360 - loss: 0.1784 - val_Accuracy: 0.8432 - val_loss: 0.4381
Epoch 10/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9520 - loss: 0.1403 - val_Accuracy: 0.8305 - val_loss: 0.4233
Epoch 11/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9541 - loss: 0.1306 - val_Accuracy: 0.8475 - val_loss: 0.4865
Epoch 12/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.9682 - loss: 0.0919 - val_Accuracy: 0.8051 - val_loss: 0.4931
Epoch 13/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9721 - loss: 0.0901 - val_Accuracy: 0.8390 - val_loss: 0.5425
Epoch 14/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9850 - loss: 0.0508 - val_Accuracy: 0.8008 - val_loss: 0.5518
Epoch 15/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9909 - loss: 0.0366 - val_Accuracy: 0.8178 - val_loss: 0.6232
Epoch 16/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9986 - loss: 0.0231 - val_Accuracy: 0.8220 - val_loss: 0.6909
Epoch 17/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 1.0000 - loss: 0.0185 - val_Accuracy: 0.8136 - val_loss: 0.7091
Epoch 18/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 1.0000 - loss: 0.0125 - val_Accuracy: 0.8093 - val_loss: 0.7568
Epoch 19/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 1.0000 - loss: 0.0095 - val_Accuracy: 0.8178 - val_loss: 0.7999
Epoch 20/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 1.0000 - loss: 0.0072 - val_Accuracy: 0.8178 - val_loss: 0.8538

In [ ]:
loss, accuracy = model2.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - Accuracy: 0.8463 - loss: 0.7030
Test Accuracy: 0.8571428656578064

In [ ]:
y_pred2= (model2.predict(x_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred2))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step
Accuracy: 0.8571428571428571

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.96      0.93       244
           1       0.74      0.50      0.60        50

    accuracy                           0.88       294
   macro avg       0.82      0.73      0.76       294
weighted avg       0.88      0.88      0.88       294


Confusion Matrix:
 [[235   9]
 [ 25  25]]

In [ ]:
loss_model1, accuracy_model1 = model.evaluate(x_test, y_test, verbose=0)
loss_model2, accuracy_model2 = model2.evaluate(x_test, y_test, verbose=0)

print(f"Model 1 Test Accuracy: {accuracy_model1:.4f}")
print(f"Model 2 Test Accuracy: {accuracy_model2:.4f}")

Model 1 Test Accuracy: 0.8844
Model 2 Test Accuracy: 0.8571