In [1]:
from google.colab import files
uploaded=files.upload()

Saving spam.csv to spam.csv

In [2]:
uploaded.keys()

dict_keys(['spam.csv'])

In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('spam.csv', encoding='latin-1')

In [8]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [9]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [10]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

In [11]:
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [12]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

/tmp/ipython-input-3713076822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [13]:
df

      label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0              Will Ì_ b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [14]:
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   int64
 1   message  5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB

In [16]:
df['label'].value_counts()

label
0    4825
1     747
Name: count, dtype: int64

In [19]:
x=df['message']
y=df['label']

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [23]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=3000)

In [24]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
model=MultinomialNB()

In [27]:
model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [28]:
y_pred=model.predict(X_test_tfidf)

In [29]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [41]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score

In [42]:
accuaracy=accuracy_score(y_test,y_pred)

In [43]:
accuaracy

0.97847533632287

In [44]:
precision=precision_score(y_test,y_pred)
precision

1.0

In [46]:
recall=recall_score(y_test,y_pred)
recall

0.84

In [47]:
f1=f1_score(y_test,y_pred)
f1

0.9130434782608695

In [35]:
classification=classification_report(y_test,y_pred)
print(classification)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       1.00      0.84      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [36]:
new_messages = [
    "Congratulations! You have won $5000 cash!",
    "Hey, are we meeting tomorrow?"
]

In [37]:
new_tfidf = vectorizer.transform(new_messages)

In [38]:
predictions = model.predict(new_tfidf)

In [39]:
for msg, pred in zip(new_messages, predictions):
    print(f"Message: {msg}")
    print("Prediction:", "Spam" if pred == 1 else "Ham")
    print()

Message: Congratulations! You have won $5000 cash!
Prediction: Spam

Message: Hey, are we meeting tomorrow?
Prediction: Ham